### ISSUE TITLE
Typo on Chapter 9.2 PCA,  runPCA(..., BSPARAM=RandomParam(), name='')

### ISSUE THREAD

**Issue by estellad** [Bioconductor/OSCABase#64]
Hi there, according to the documentation of BiocSingularParam classes, BSPARAM=RandomParam() corresponds to a name of rsvd, instead of irlba (IrlbaParam()). This is a minor edit to make :)

**Comment by estellad** [comment]
The developed version has fixed it :)

**Comment by PeteHaitch** [comment]
Can you please share a link to where you read this? It would be good to fix in the release version if it's still a problem.

**Comment by estellad** [comment]
Hi PeteHaitch, 

Here is the link [https://bioconductor.org/books/3.12/OSCA/dimensionality-reduction.html#principal-components-analysis](https://bioconductor.org/books/3.12/OSCA/dimensionality-reduction.html#principal-components-analysis)

     sce.zeisel <- runPCA(sce.zeisel, subset_row=top.zeisel, BSPARAM=**RandomParam()**, name=**"IRLBA"**)

The code is right before Chapter 9.3.

**Comment by PeteHaitch** [comment]
Thanks @estellad.

That version of the book refers to Bioconductor version 3.12 (you can see this in the URL), which dates back to October, 2020.
This version of the book is out-dated and will not be updated.
We publish a new version of the book with each Bioconductor release (you can see a list of releases at https://www.bioconductor.org/about/release-announcements/).

You can always access the current version of the book by going to https://osca.bioconductor.org/, which will re-direct you to https://bioconductor.org/books/release/OSCA/.
The development version of the book (which will become the next release version of the book in late-April, 2023) is also available from https://bioconductor.org/books/devel/OSCA/.

**Comment by estellad** [comment]
Thank you very much for the information @PeteHaitch !
